// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwc5lBkZ8lTWant02BUwVHrM2iXPMbQdQ',
    appId: '1:769570251246:web:e648ac06a4ed0a6dc32eff',
    messagingSenderId: '769570251246',
    projectId: 'fir-test-3e1ef',
    authDomain: 'fir-test-3e1ef.firebaseapp.com',
    storageBucket: 'fir-test-3e1ef.appspot.com',
    measurementId: 'G-VGLREXJX3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6q91lyBWxVV1HyIpxmtZFIvFygZ_e9Vw',
    appId: '1:769570251246:android:acd9a96d468e91afc32eff',
    messagingSenderId: '769570251246',
    projectId: 'fir-test-3e1ef',
    storageBucket: 'fir-test-3e1ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZw7QPGbqYhqlvge8IOX71n7dojp32JAg',
    appId: '1:769570251246:ios:abe7592de0210bf5c32eff',
    messagingSenderId: '769570251246',
    projectId: 'fir-test-3e1ef',
    storageBucket: 'fir-test-3e1ef.appspot.com',
    iosClientId: '769570251246-ig8kl9e3p30kdkfbsapj8h69c7lm2jaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZw7QPGbqYhqlvge8IOX71n7dojp32JAg',
    appId: '1:769570251246:ios:3c8de3fcf3108d6ac32eff',
    messagingSenderId: '769570251246',
    projectId: 'fir-test-3e1ef',
    storageBucket: 'fir-test-3e1ef.appspot.com',
    iosClientId: '769570251246-8eem97o1a0t3r55n4ncrkibe0m6ce202.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
