name: ui
description: A sample command-line application.
publish_to: none
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  fl_chart: ^0.40.0
  go_router: ^11.0.0
  model:
    path: ../model

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
